{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:43.589125900Z",
     "start_time": "2023-08-20T17:55:43.574863800Z"
    }
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "import datetime\n",
    "import pytz\n",
    "import numpy as np\n",
    "import pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "outputs": [
    {
     "data": {
      "text/plain": "   id Age Height (cm) Weight (kg)  Gender Dominant hand  \\\n0   2  27         175          80    male         right   \n0   3  27         173          69    male         right   \n0   4  25         175          90    male         right   \n0   5  35         189          80    male         right   \n0   6  27         170          66    male         right   \n0   7  28         184          74    male         right   \n0   8  27         172          64  female          left   \n0   9  26         181          75    male         right   \n0  10  28         178          76    male         right   \n0  11  26         171          54  female         right   \n0  13  28         181          82    male         right   \n0  14  27         180          80    male         right   \n0  15  28         186          83    male         right   \n0  16  24         184          69    male         right   \n0  17  29         165          55  female         right   \n\n  Did you drink coffee today Did you drink coffee within the last hour  \\\n0                         NO                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n0                        YES                                        NO   \n0                        YES                                        NO   \n0                         NO                                        NO   \n0                        YES                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n0                        YES                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n0                         NO                                        NO   \n\n  Did you do any sports today Are you a smoker  \\\n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO              YES   \n0                         YES               NO   \n0                         YES               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n0                          NO               NO   \n\n  Did you smoke within the last hour Do you feel ill today  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                   YES  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  \n0                                 NO                    NO  ",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>Age</th>\n      <th>Height (cm)</th>\n      <th>Weight (kg)</th>\n      <th>Gender</th>\n      <th>Dominant hand</th>\n      <th>Did you drink coffee today</th>\n      <th>Did you drink coffee within the last hour</th>\n      <th>Did you do any sports today</th>\n      <th>Are you a smoker</th>\n      <th>Did you smoke within the last hour</th>\n      <th>Do you feel ill today</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2</td>\n      <td>27</td>\n      <td>175</td>\n      <td>80</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>3</td>\n      <td>27</td>\n      <td>173</td>\n      <td>69</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>4</td>\n      <td>25</td>\n      <td>175</td>\n      <td>90</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>5</td>\n      <td>35</td>\n      <td>189</td>\n      <td>80</td>\n      <td>male</td>\n      <td>right</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>6</td>\n      <td>27</td>\n      <td>170</td>\n      <td>66</td>\n      <td>male</td>\n      <td>right</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>7</td>\n      <td>28</td>\n      <td>184</td>\n      <td>74</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>8</td>\n      <td>27</td>\n      <td>172</td>\n      <td>64</td>\n      <td>female</td>\n      <td>left</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>9</td>\n      <td>26</td>\n      <td>181</td>\n      <td>75</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>YES</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>10</td>\n      <td>28</td>\n      <td>178</td>\n      <td>76</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>11</td>\n      <td>26</td>\n      <td>171</td>\n      <td>54</td>\n      <td>female</td>\n      <td>right</td>\n      <td>YES</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>13</td>\n      <td>28</td>\n      <td>181</td>\n      <td>82</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>14</td>\n      <td>27</td>\n      <td>180</td>\n      <td>80</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>15</td>\n      <td>28</td>\n      <td>186</td>\n      <td>83</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>16</td>\n      <td>24</td>\n      <td>184</td>\n      <td>69</td>\n      <td>male</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>17</td>\n      <td>29</td>\n      <td>165</td>\n      <td>55</td>\n      <td>female</td>\n      <td>right</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n      <td>NO</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
     },
     "execution_count": 83,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read the txt readme files\n",
    "\n",
    "demo=pd.DataFrame()\n",
    "\n",
    "numbers=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17]\n",
    "\n",
    "for i in numbers:\n",
    "    filename = 'data\\WESAD\\S%i\\S%i_readme.txt'%(i,i)\n",
    "\n",
    "#filename = 'data\\WESAD\\S8\\S8_readme.txt'\n",
    "\n",
    "    with open(filename, 'r') as file:\n",
    "        lines = file.readlines()\n",
    "\n",
    "    subject_number = int(os.path.basename(filename).split('S')[1].split('_')[0])\n",
    "    data = {'id': subject_number}\n",
    "    current_header = None\n",
    "\n",
    "    for line in lines:\n",
    "        parts = line.strip().split(':')  # Split using ':' as delimiter\n",
    "        if len(parts) == 1:  # If ':' is not found, split using '?' as delimiter\n",
    "            parts = line.strip().split('?')\n",
    "        if len(parts) > 1:\n",
    "            header = parts[0].strip()  # Extract the column header\n",
    "            value = ':'.join(parts[1:]).strip()  # Join remaining parts as value\n",
    "            data[header] = value\n",
    "\n",
    "    # Create a Pandas DataFrame\n",
    "    user_df = pd.DataFrame([data])\n",
    "    # before the next user, add this user_df to the total dataframe\n",
    "    demo = pd.concat([demo, user_df])\n",
    "\n",
    "demo = demo.drop(columns=['Stress condition / TSST interview part'])\n",
    "demo"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:43.646449500Z",
     "start_time": "2023-08-20T17:55:43.591133700Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "outputs": [
    {
     "data": {
      "text/plain": "    id  PA_Score  NA_Score\n0    2        20        12\n1    2        24        15\n2    2        15        10\n3    2        31        38\n4    2        23        14\n..  ..       ...       ...\n0   17        20        12\n1   17        24        15\n2   17        15        10\n3   17        31        38\n4   17        23        14\n\n[75 rows x 3 columns]",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>PA_Score</th>\n      <th>NA_Score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2</td>\n      <td>20</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>24</td>\n      <td>15</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>15</td>\n      <td>10</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2</td>\n      <td>31</td>\n      <td>38</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2</td>\n      <td>23</td>\n      <td>14</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>17</td>\n      <td>20</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>17</td>\n      <td>24</td>\n      <td>15</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>17</td>\n      <td>15</td>\n      <td>10</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>17</td>\n      <td>31</td>\n      <td>38</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>17</td>\n      <td>23</td>\n      <td>14</td>\n    </tr>\n  </tbody>\n</table>\n<p>75 rows × 3 columns</p>\n</div>"
     },
     "execution_count": 84,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read the PANAS self questionnaires csv files\n",
    "\n",
    "# PANAS scores can range from 10 to 50, with higher scores representing higher levels of positive or negative affect, respectively.\n",
    "\n",
    "def calculate_panas_scores_from_dataframe(df):\n",
    "\n",
    "    positive_headers = [\"Interested\", \"Inspired\", \"Guilty\", \"Excited\", \"Irritable\", \"Alert\", \"Attentive\", \"Jittery\", \"Afraid\", \"Stressed\"]\n",
    "    negative_headers = [\"Active\", \"Distressed\", \"Annoyed\", \"Strong\", \"Scared\", \"Hostile\", \"Proud\", \"Enthusiastic\", \"Ashamed\", \"Sad\", \"(Angry)\", \"(Irritated)\"]\n",
    "\n",
    "    df[positive_headers + negative_headers] = df[positive_headers + negative_headers].apply(pd.to_numeric, errors='coerce').fillna(0)\n",
    "\n",
    "    pa_score = df[positive_headers].astype(int).sum(axis=1)\n",
    "    na_score = df[negative_headers].astype(int).sum(axis=1)\n",
    "\n",
    "    df['PA_Score'] = pa_score\n",
    "    df['NA_Score'] = na_score\n",
    "\n",
    "    return df\n",
    "\n",
    "numbers=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17]\n",
    "\n",
    "panas=pd.DataFrame()\n",
    "\n",
    "for user in numbers:\n",
    "    filename = 'data\\WESAD\\S%i\\S%i_quest.csv'%(i,i)\n",
    "    #user_df=pd.DataFrame()\n",
    "\n",
    "    lines_to_read = 5\n",
    "    data = []\n",
    "\n",
    "    header_mapping = {\n",
    "    1: \"Active\",\n",
    "    2: \"Distressed\",\n",
    "    3: \"Interested\",\n",
    "    4: \"Inspired\",\n",
    "    5: \"Annoyed\",\n",
    "    6: \"Strong\",\n",
    "    7: \"Guilty\",\n",
    "    8: \"Scared\",\n",
    "    9: \"Hostile\",\n",
    "    10: \"Excited\",\n",
    "    11: \"Proud\",\n",
    "    12: \"Irritable\",\n",
    "    13: \"Enthusiastic\",\n",
    "    14: \"Ashamed\",\n",
    "    15: \"Alert\",\n",
    "    16: \"Nervous\",\n",
    "    17: \"Determined\",\n",
    "    18: \"Attentive\",\n",
    "    19: \"Jittery\",\n",
    "    20: \"Afraid\",\n",
    "    21: \"Stressed\",\n",
    "    22: \"Frustrated\",\n",
    "    23: \"Happy\",\n",
    "    24: \"Sad\",\n",
    "    25: \"(Angry)\",\n",
    "    26: \"(Irritated)\"\n",
    "}\n",
    "\n",
    "    with open(filename, 'r') as csvfile:\n",
    "        lines_read = 0\n",
    "        for line in csvfile:\n",
    "            if lines_read >= lines_to_read:\n",
    "                break\n",
    "            if line.strip().startswith('# PANAS'):\n",
    "                values = line.strip().split(';')[1:]\n",
    "                data.append(values)\n",
    "                lines_read += 1\n",
    "\n",
    "    user_df = pd.DataFrame(data, columns=[header_mapping[i] for i in range(1, len(data[0]) + 1)])\n",
    "    user_df['id'] = user\n",
    "\n",
    "    # before the next user, add this user_df to the total dataframe\n",
    "    panas = pd.concat([panas, user_df])\n",
    "\n",
    "panas = calculate_panas_scores_from_dataframe(panas)\n",
    "panas = panas.drop(panas.iloc[:, 0:26],axis = 1)\n",
    "\n",
    "panas"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:43.738164900Z",
     "start_time": "2023-08-20T17:55:43.656659700Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "outputs": [
    {
     "data": {
      "text/plain": "    id stai_stress_category\n0    2        Above average\n1    2        Below average\n2    2        Above average\n3    2              Average\n4    2        Above average\n..  ..                  ...\n0   17        Below average\n1   17        Above average\n2   17        Below average\n3   17              Average\n4   17        Below average\n\n[75 rows x 2 columns]",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>stai_stress_category</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2</td>\n      <td>Above average</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>Below average</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>Above average</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2</td>\n      <td>Average</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2</td>\n      <td>Above average</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>17</td>\n      <td>Below average</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>17</td>\n      <td>Above average</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>17</td>\n      <td>Below average</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>17</td>\n      <td>Average</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>17</td>\n      <td>Below average</td>\n    </tr>\n  </tbody>\n</table>\n<p>75 rows × 2 columns</p>\n</div>"
     },
     "execution_count": 85,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read the STAI self questionnaires csv files\n",
    "\n",
    "# to calculate the total stress score simply sum per row\n",
    "\n",
    "numbers=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17]\n",
    "\n",
    "stai=pd.DataFrame()\n",
    "\n",
    "for user in numbers:\n",
    "    filename = 'data\\WESAD\\S%i\\S%i_quest.csv'%(user,user)\n",
    "\n",
    "    lines_to_read = 5\n",
    "    data = []\n",
    "\n",
    "    with open(filename, 'r') as csvfile:\n",
    "        lines_read = 0\n",
    "        for line in csvfile:\n",
    "            if lines_read >= lines_to_read:\n",
    "                break\n",
    "            if line.strip().startswith('# STAI'):\n",
    "                values = line.strip().split(';')[1:]\n",
    "                data.append(values)\n",
    "                lines_read += 1\n",
    "\n",
    "    user_df = pd.DataFrame(data)\n",
    "    user_df = user_df.iloc[:, 0:6]\n",
    "    user_df['id'] = user\n",
    "\n",
    "    # before the next user, add this user_df to the total dataframe\n",
    "    stai = pd.concat([stai, user_df])\n",
    "\n",
    "for column in stai.columns:\n",
    "    stai[column] = pd.to_numeric(stai[column], errors='coerce')\n",
    "\n",
    "\n",
    "stai['stai_stress'] = stai.iloc[:, 0:6].sum(axis=1)\n",
    "stai = stai.iloc[:, 6:]\n",
    "\n",
    "mean_stai = stai['stai_stress'].mean()\n",
    "std_stai = stai['stai_stress'].std()\n",
    "\n",
    "def get_stai_category(score):\n",
    "    if score < mean_stai-0.5*std_stai:\n",
    "        return \"Below average\"\n",
    "    if score > mean_stai+0.5*std_stai:\n",
    "        return \"Above average\"\n",
    "    return \"Average\"\n",
    "\n",
    "stai['stai_stress_category'] = stai['stai_stress'].apply(lambda score: get_stai_category(score))\n",
    "\n",
    "stai = stai.drop(columns=['stai_stress'])\n",
    "\n",
    "stai"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:43.768504600Z",
     "start_time": "2023-08-20T17:55:43.704297700Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "outputs": [],
   "source": [
    "def adds_datetime_col_acc(df):\n",
    "    timestamp_utc = df.iloc[0, 0]\n",
    "    datetime_utc = datetime.datetime.utcfromtimestamp(timestamp_utc)\n",
    "    datetime_utc = datetime_utc.replace(tzinfo=pytz.utc)\n",
    "    target_timezone = pytz.timezone('America/New_York')\n",
    "    datetime_local = datetime_utc.astimezone(target_timezone)\n",
    "    df['Date'] = datetime_local.strftime('%Y-%m-%d %H:%M:%S %Z')\n",
    "    df = df.iloc[1:]\n",
    "    starting_date = df.iloc[0,3]\n",
    "    num_rows = df.shape[0]\n",
    "    date_range = pd.date_range(start=starting_date, periods=num_rows, freq='S')\n",
    "    df['date'] = pd.DataFrame({'date': date_range})\n",
    "    df = df.drop(columns=\"Date\")\n",
    "\n",
    "    return df\n",
    "\n",
    "def adds_datetime_col(df):\n",
    "    timestamp_utc = df.iloc[0, 0]\n",
    "    datetime_utc = datetime.datetime.utcfromtimestamp(timestamp_utc)\n",
    "    datetime_utc = datetime_utc.replace(tzinfo=pytz.utc)\n",
    "    target_timezone = pytz.timezone('America/New_York')\n",
    "    datetime_local = datetime_utc.astimezone(target_timezone)\n",
    "    df['Date'] = datetime_local.strftime('%Y-%m-%d %H:%M:%S %Z')\n",
    "    df = df.iloc[1:]\n",
    "    starting_date = df.iloc[0,1]\n",
    "    num_rows = df.shape[0]\n",
    "    date_range = pd.date_range(start=starting_date, periods=num_rows, freq='S')\n",
    "    df['date'] = pd.DataFrame({'date': date_range})\n",
    "    df = df.drop(columns=\"Date\")\n",
    "\n",
    "    return df"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:43.791090200Z",
     "start_time": "2023-08-20T17:55:43.767628900Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n",
      "C:\\Users\\Christina\\anaconda3\\lib\\site-packages\\dateutil\\parser\\_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  warnings.warn(\"tzname {tzname} identified but not understood.  \"\n",
      "C:\\Users\\CHRIST~1\\AppData\\Local\\Temp/ipykernel_21792/2861872451.py:28: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = pd.DataFrame({'date': date_range})\n"
     ]
    },
    {
     "data": {
      "text/plain": "           0     1     2                date  id       EDA    BVP  HR    TEMP\n0       32.0  32.0  32.0 2017-05-22 03:15:26   2  4.000000  64.00 NaN    4.00\n1       29.0  -6.0  55.0 2017-05-22 03:15:27   2  0.000000  -0.00 NaN  382.18\n2       28.0  -6.0  55.0 2017-05-22 03:15:28   2  0.328021  -0.00 NaN  382.18\n3       28.0  -6.0  55.0 2017-05-22 03:15:29   2  0.410026  -0.00 NaN  382.18\n4       28.0  -6.0  55.0 2017-05-22 03:15:30   2  0.433090  -0.00 NaN  382.18\n...      ...   ...   ...                 ...  ..       ...    ...  ..     ...\n462821   NaN   NaN   NaN 2017-08-16 11:53:03  17       NaN -53.77 NaN     NaN\n462822   NaN   NaN   NaN 2017-08-16 11:53:04  17       NaN -53.29 NaN     NaN\n462823   NaN   NaN   NaN 2017-08-16 11:53:05  17       NaN -52.71 NaN     NaN\n462824   NaN   NaN   NaN 2017-08-16 11:53:06  17       NaN -52.26 NaN     NaN\n462825   NaN   NaN   NaN 2017-08-16 11:53:07  17       NaN -52.11 NaN     NaN\n\n[6844578 rows x 9 columns]",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>date</th>\n      <th>id</th>\n      <th>EDA</th>\n      <th>BVP</th>\n      <th>HR</th>\n      <th>TEMP</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>32.0</td>\n      <td>32.0</td>\n      <td>32.0</td>\n      <td>2017-05-22 03:15:26</td>\n      <td>2</td>\n      <td>4.000000</td>\n      <td>64.00</td>\n      <td>NaN</td>\n      <td>4.00</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>29.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>2017-05-22 03:15:27</td>\n      <td>2</td>\n      <td>0.000000</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>2017-05-22 03:15:28</td>\n      <td>2</td>\n      <td>0.328021</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>2017-05-22 03:15:29</td>\n      <td>2</td>\n      <td>0.410026</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>2017-05-22 03:15:30</td>\n      <td>2</td>\n      <td>0.433090</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>462821</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2017-08-16 11:53:03</td>\n      <td>17</td>\n      <td>NaN</td>\n      <td>-53.77</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>462822</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2017-08-16 11:53:04</td>\n      <td>17</td>\n      <td>NaN</td>\n      <td>-53.29</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>462823</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2017-08-16 11:53:05</td>\n      <td>17</td>\n      <td>NaN</td>\n      <td>-52.71</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>462824</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2017-08-16 11:53:06</td>\n      <td>17</td>\n      <td>NaN</td>\n      <td>-52.26</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>462825</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2017-08-16 11:53:07</td>\n      <td>17</td>\n      <td>NaN</td>\n      <td>-52.11</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>6844578 rows × 9 columns</p>\n</div>"
     },
     "execution_count": 87,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read E4 data\n",
    "\n",
    "numbers=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17]\n",
    "\n",
    "total_df = pd.DataFrame()\n",
    "\n",
    "for user in numbers:\n",
    "    e4_acc = pd.read_csv('data\\WESAD\\S%i\\S%i_E4_Data\\ACC.csv'%(user,user), header=None)\n",
    "    e4_acc = adds_datetime_col_acc(e4_acc)\n",
    "\n",
    "    e4_eda = pd.read_csv('data\\WESAD\\S%i\\S%i_E4_Data\\EDA.csv'%(user,user), header=None)\n",
    "    e4_eda = e4_eda.rename(columns={e4_eda.columns[0]: 'EDA'})\n",
    "    e4_eda = adds_datetime_col(e4_eda)\n",
    "    e4_eda['id'] = user\n",
    "    e4_eda =e4_eda.groupby(['id','date'])['EDA'].mean().reset_index()\n",
    "    data = pd.merge(e4_acc, e4_eda, how='outer', on='date')\n",
    "\n",
    "    e4_bvp = pd.read_csv('data\\WESAD\\S%i\\S%i_E4_Data\\BVP.csv'%(user,user), header=None)\n",
    "    e4_bvp = e4_bvp.rename(columns={e4_bvp.columns[0]: 'BVP'})\n",
    "    e4_bvp = adds_datetime_col(e4_bvp)\n",
    "    data = pd.merge(data, e4_bvp, how='outer', on='date')\n",
    "\n",
    "    e4_hr = pd.read_csv('data\\WESAD\\S%i\\S%i_E4_Data\\HR.csv'%(user,user), header=None)\n",
    "    e4_hr = e4_hr.rename(columns={e4_hr.columns[0]: 'HR'})\n",
    "    e4_hr = adds_datetime_col(e4_hr)\n",
    "    data = pd.merge(data, e4_hr, how='outer', on='date')\n",
    "\n",
    "    e4_temp = pd.read_csv('data\\WESAD\\S%i\\S%i_E4_Data\\TEMP.csv'%(user,user), header=None)\n",
    "    e4_temp = e4_temp.rename(columns={e4_temp.columns[0]: 'TEMP'})\n",
    "    e4_temp = adds_datetime_col(e4_temp)\n",
    "    data = pd.merge(data, e4_temp, how='outer', on='date')\n",
    "\n",
    "    data['id'] = user\n",
    "\n",
    "    # before the next user, add this user_df to the total dataframe\n",
    "    total_df = pd.concat([total_df, data])\n",
    "\n",
    "total_df"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:52.355731100Z",
     "start_time": "2023-08-20T17:55:43.779542600Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "outputs": [
    {
     "data": {
      "text/plain": "Index([0, 1, 2, 'date', 'id', 'EDA', 'BVP', 'HR', 'TEMP'], dtype='object')"
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_df.columns"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:52.399763Z",
     "start_time": "2023-08-20T17:55:52.357878100Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "outputs": [
    {
     "data": {
      "text/plain": "        id                date     0     1     2       EDA    BVP     HR  \\\n0        2 2017-05-22 03:15:26  32.0  32.0  32.0  4.000000  64.00    NaN   \n1        2 2017-05-22 03:15:27  29.0  -6.0  55.0  0.000000  -0.00    NaN   \n2        2 2017-05-22 03:15:28  28.0  -6.0  55.0  0.328021  -0.00    NaN   \n3        2 2017-05-22 03:15:29  28.0  -6.0  55.0  0.410026  -0.00    NaN   \n4        2 2017-05-22 03:15:30  28.0  -6.0  55.0  0.433090  -0.00    NaN   \n...     ..                 ...   ...   ...   ...       ...    ...    ...   \n219606  13                 NaT   6.0   7.0  63.0       NaN -36.33  75.90   \n223560  14                 NaT   5.0  21.0  58.0       NaN  -3.77  78.52   \n212568  15                 NaT  19.0   7.0  57.0       NaN   3.91  78.55   \n227430  16                 NaT  10.0   5.0  63.0       NaN -31.04  82.43   \n231414  17                 NaT  -3.0  13.0  62.0       NaN -52.21  73.65   \n\n          TEMP  \n0         4.00  \n1       382.18  \n2       382.18  \n3       382.18  \n4       382.18  \n...        ...  \n219606   34.18  \n223560   31.23  \n212568   28.97  \n227430   29.49  \n231414   31.57  \n\n[6844578 rows x 9 columns]",
      "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>id</th>\n      <th>date</th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>EDA</th>\n      <th>BVP</th>\n      <th>HR</th>\n      <th>TEMP</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2</td>\n      <td>2017-05-22 03:15:26</td>\n      <td>32.0</td>\n      <td>32.0</td>\n      <td>32.0</td>\n      <td>4.000000</td>\n      <td>64.00</td>\n      <td>NaN</td>\n      <td>4.00</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>2017-05-22 03:15:27</td>\n      <td>29.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>0.000000</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>2017-05-22 03:15:28</td>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>0.328021</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2</td>\n      <td>2017-05-22 03:15:29</td>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>0.410026</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2</td>\n      <td>2017-05-22 03:15:30</td>\n      <td>28.0</td>\n      <td>-6.0</td>\n      <td>55.0</td>\n      <td>0.433090</td>\n      <td>-0.00</td>\n      <td>NaN</td>\n      <td>382.18</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>219606</th>\n      <td>13</td>\n      <td>NaT</td>\n      <td>6.0</td>\n      <td>7.0</td>\n      <td>63.0</td>\n      <td>NaN</td>\n      <td>-36.33</td>\n      <td>75.90</td>\n      <td>34.18</td>\n    </tr>\n    <tr>\n      <th>223560</th>\n      <td>14</td>\n      <td>NaT</td>\n      <td>5.0</td>\n      <td>21.0</td>\n      <td>58.0</td>\n      <td>NaN</td>\n      <td>-3.77</td>\n      <td>78.52</td>\n      <td>31.23</td>\n    </tr>\n    <tr>\n      <th>212568</th>\n      <td>15</td>\n      <td>NaT</td>\n      <td>19.0</td>\n      <td>7.0</td>\n      <td>57.0</td>\n      <td>NaN</td>\n      <td>3.91</td>\n      <td>78.55</td>\n      <td>28.97</td>\n    </tr>\n    <tr>\n      <th>227430</th>\n      <td>16</td>\n      <td>NaT</td>\n      <td>10.0</td>\n      <td>5.0</td>\n      <td>63.0</td>\n      <td>NaN</td>\n      <td>-31.04</td>\n      <td>82.43</td>\n      <td>29.49</td>\n    </tr>\n    <tr>\n      <th>231414</th>\n      <td>17</td>\n      <td>NaT</td>\n      <td>-3.0</td>\n      <td>13.0</td>\n      <td>62.0</td>\n      <td>NaN</td>\n      <td>-52.21</td>\n      <td>73.65</td>\n      <td>31.57</td>\n    </tr>\n  </tbody>\n</table>\n<p>6844578 rows × 9 columns</p>\n</div>"
     },
     "execution_count": 89,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_df = total_df[['id', 'date', 0, 1, 2, 'EDA', 'BVP', 'HR', 'TEMP']]\n",
    "total_df = total_df.sort_values(by='date',ascending=True)\n",
    "total_df['date'] = pd.to_datetime(total_df['date'])\n",
    "total_df"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:53.611199600Z",
     "start_time": "2023-08-20T17:55:52.374700100Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:53.627681Z",
     "start_time": "2023-08-20T17:55:53.612249400Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:53.649925300Z",
     "start_time": "2023-08-20T17:55:53.627843500Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-08-20T17:55:53.702112600Z",
     "start_time": "2023-08-20T17:55:53.643201400Z"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
